# Generated by Django 3.2 on 2021-05-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cmp_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_fi',
            name='occas',
            field=models.TextField(choices=[('1', 'OCCAS'), ('2', 'NON OCCAS')], default='NO OCCAS'),
        ),
    ]
