# Generated by Django 3.2 on 2021-05-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_flight_fi_occas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CMP_DISPATCHER',
        ),
    ]
