# Generated by Django 3.2 on 2021-05-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cmp_dispatcher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CMP_DISPATCHER',
            new_name='DISPATCHER',
        ),
    ]
