# Generated by Django 3.2 on 2021-05-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_cmp_dispatcher_dispatcher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DISPATCHER',
        ),
    ]
