# Generated by Django 3.2 on 2021-05-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comp_dispatcher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comp_dispatcher',
            table='COMP_DISPATCHER',
        ),
    ]
