# Generated by Django 3.2 on 2021-05-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_comp_dispatcher_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COMP_DISPATCHER',
        ),
    ]
