# Generated by Django 3.2 on 2021-05-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comp_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_fi',
            name='escale',
            field=models.TextField(blank=True, db_column='ESCALE (IATA)', default='/', null=True),
        ),
        migrations.AlterField(
            model_name='flight_fi',
            name='occas',
            field=models.TextField(choices=[('1', 'OCCAS'), ('2', 'NON OCCAS')], default='/'),
        ),
    ]
