# Generated by Django 3.2 on 2021-05-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chg_fi_chg_ssim_comp_dispatcher_flight_fi_flight_occas_flight_ssim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHG_FI',
        ),
        migrations.DeleteModel(
            name='CHG_SSIM',
        ),
        migrations.DeleteModel(
            name='COMP_DISPATCHER',
        ),
        migrations.DeleteModel(
            name='FLIGHT_FI',
        ),
        migrations.DeleteModel(
            name='FLIGHT_OCCAS',
        ),
        migrations.DeleteModel(
            name='FLIGHT_SSIM',
        ),
    ]
