# Generated by Django 3.2 on 2021-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_chg_fi_chg_ssim_comp_dispatcher_flight_fi_flight_occas_flight_ssim'),
    ]

    operations = [
        migrations.AddField(
            model_name='chg_fi',
            name='_id',
            field=models.IntegerField(blank=True, db_column='ID', null=True),
        ),
        migrations.AddField(
            model_name='chg_ssim',
            name='_id',
            field=models.IntegerField(blank=True, db_column='ID', null=True),
        ),
        migrations.AlterField(
            model_name='chg_fi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chg_ssim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
