# Generated by Django 3.2 on 2021-05-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210503_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='chg_ssim',
            name='status',
            field=models.TextField(blank=True, db_column='STATUS_x', null=True),
        ),
        migrations.AddField(
            model_name='flight_occas',
            name='type_avion',
            field=models.TextField(blank=True, db_column='TYPE AVION', null=True),
        ),
    ]
