# Generated by Django 3.2 on 2021-05-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210504_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chg_fi',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='chg_ssim',
            name='_id',
        ),
        migrations.AlterField(
            model_name='chg_fi',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chg_ssim',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False),
        ),
    ]
