# Generated by Django 3.2 on 2021-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_occas',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
