# Generated by Django 3.2 on 2021-05-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_flight_occas_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comp_dispatcher',
            table='COMP_DISPACTHER',
        ),
    ]
