# Generated by Django 3.2 on 2021-05-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_comp_dispatcher_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COMP_DISPATCHER',
            new_name='COMP_DISPACTHER',
        ),
    ]
