# Generated by Django 3.2 on 2021-05-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_comp_dispatcher_comp_dispacther'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COMP_DISPACTHER',
            new_name='COMP_DISPATCHER',
        ),
        migrations.AlterModelTable(
            name='comp_dispatcher',
            table='COMP_DISPATCHER',
        ),
    ]
