# Generated by Django 3.2 on 2021-05-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210510_1655'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comp_dispatcher',
            table='COMP_DISPACTHER',
        ),
    ]
