# Generated by Django 3.2 on 2021-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_comp_dispatcher_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_occas',
            name='date_last_edit',
            field=models.DateTimeField(blank=True, db_column='DATE LAST EDIT', null=True),
        ),
        migrations.AddField(
            model_name='flight_occas',
            name='user_last_edit',
            field=models.TextField(blank=True, db_column='USER LAST EDIT', null=True),
        ),
    ]
