# Generated by Django 3.2 on 2021-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210511_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_dispatcher',
            name='monnaie',
            field=models.TextField(blank=True, choices=[(1, 'DZD'), (2, 'USD'), (3, 'EUR')], db_column='MONNAIE'),
        ),
    ]
