# Generated by Django 3.2 on 2021-05-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_comp_dispatcher_monnaie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FLIGHT_ASSIST',
        ),
    ]
