# Generated by Django 3.2 on 2021-05-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_flight_assist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FLIGHT_ASSIST',
        ),
    ]
