# Generated by Django 3.2 on 2021-05-15 18:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_flight_assist_mtow_tonnes_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_assist',
            name='date_arrivee',
            field=models.DateField(blank=True, db_column='DATE ARRIVEE', null=True, validators=[core.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='flight_assist',
            name='date_cnl',
            field=models.DateTimeField(blank=True, db_column='DATE CNL', null=True, validators=[core.models.validate_date]),
        ),
    ]
