# Generated by Django 3.2 on 2021-05-18 14:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210515_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_assist',
            name='date_cnl',
            field=models.DateField(blank=True, db_column='DATE CNL', null=True, validators=[core.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='flight_assist',
            name='date_demande',
            field=models.DateField(blank=True, db_column='DATE DEMANDE', null=True),
        ),
    ]
