# Generated by Django 3.2 on 2021-05-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210518_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_assist',
            name='date_last_edit',
            field=models.DateTimeField(auto_now=True, db_column='DATE LAST EDIT', null=True),
        ),
    ]
