# Generated by Django 3.2 on 2021-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_flight_assist_date_last_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_assist',
            name='cnl_eta',
            field=models.DurationField(blank=True, db_column='CNL / ETA', null=True),
        ),
    ]
