# Generated by Django 3.2 on 2021-05-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_flight_assist_cnl_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='compagnie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comp_dispatcher'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='poste',
            field=models.TextField(blank=True, choices=[(1, 'SOUS DIRECTEUR GESTION DES ESCALES'), (2, 'CHEF DEPARTEMENT CONTRAT ET ASSISTANCE AU SOL'), (3, 'AGENT')]),
        ),
    ]
