# Generated by Django 3.2 on 2021-05-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20210518_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='etat_payment',
            field=models.BooleanField(blank=True, db_column='ETAT DE PAIEMENT', default=False, null=True),
        ),
    ]
