# Generated by Django 3.2 on 2021-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_flight_assist_etat_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_assist',
            name='psg_autre_serv_1',
            field=models.TextField(blank=True, choices=[(1, 'AMBULIFT'), (2, 'NBR GUICHET'), (3, 'VIP'), (4, 'SALON'), (5, 'CIVIERE'), (6, 'DOCUMENT METEO'), (7, 'VHF COMMUNICATION'), (8, 'MESSAGE OPS')], db_column='AUTRE SERVICE 1 (PASSAGER)', null=True),
        ),
        migrations.AlterField(
            model_name='flight_assist',
            name='psg_autre_serv_2',
            field=models.TextField(blank=True, choices=[(1, 'AMBULIFT'), (2, 'NBR GUICHET'), (3, 'VIP'), (4, 'SALON'), (5, 'CIVIERE'), (6, 'DOCUMENT METEO'), (7, 'VHF COMMUNICATION'), (8, 'MESSAGE OPS')], db_column='AUTRE SERVICE 2 (PASSAGER)', null=True),
        ),
    ]
