# Generated by Django 3.2 on 2021-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210519_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='capacite',
            field=models.PositiveIntegerField(blank=True, db_column='CAPACITE', default=0, null=True),
        ),
    ]
