# Generated by Django 3.2 on 2021-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_comp_dispatcher_solde_last_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_dispatcher',
            name='solde_last_edit',
            field=models.DateTimeField(blank=True, db_column='SOLDE_LAST_EDIT', null=True),
        ),
    ]
