# Generated by Django 3.2 on 2021-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_comp_dispatcher_solde_last_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_assist',
            name='etat_payment',
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='reponse',
            field=models.BooleanField(blank=True, db_column='REPONSE', default=False, null=True),
        ),
    ]
