# Generated by Django 3.2 on 2021-05-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20210524_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='activite',
            field=models.TextField(blank=True, db_column='ACTIVITE', null=True),
        ),
    ]
