# Generated by Django 3.2 on 2021-05-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_flight_assist_activite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_assist',
            name='activite',
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='activite',
            field=models.TextField(blank=True, db_column='ACTIVITE', null=True),
        ),
    ]
