# Generated by Django 3.2 on 2021-05-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_comp_dispatcher_user_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_dispatcher',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
