# Generated by Django 3.2 on 2021-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_comp_dispatcher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_assist',
            name='n_facture',
            field=models.PositiveIntegerField(blank=True, db_column='N° FACTURE', null=True),
        ),
    ]
