# Generated by Django 3.2 on 2021-05-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_flight_assist_n_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='retard',
            field=models.FloatField(blank=True, db_column='RETARD', default='0', null=True),
        ),
    ]
