# Generated by Django 3.2 on 2021-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_flight_assist_annulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ACC_SALON',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ACU',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='AGENT_COORD',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='AGENT_OP_QUALIF',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='AGENT_SERV_PASSAGE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='AGENT_SERV_PISTE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ARRANGEMENT_CAB_100',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ARRANGEMENT_CAB_200',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ARRANGEMENT_CAB_300',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ASSIST_TRANSIT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ASSIST_UM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ASSIST_VIP',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ASSIST_WCH',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ASU_BIG_PORT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ASU_MOY_PORT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='CAMION_ELEV',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='CHARIOT_BAG',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='CIVIERE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='COMM_SOL_COCKPIT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='CONTAINER_PALETTE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='DB_MANIP_ULD',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='DEPORTEE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='DOSS_VOL_IMP',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ELEV_FOURCHE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='GPU',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='HUM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ID_BAG_100',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='ID_BAG_200',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_10_30_COM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_10_30_TECH',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_10_COM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_10_TECH',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_150_250_COM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_150_250_TECH',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_250_COM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_250_TECH',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_30_50_COM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_30_50_TECH',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_50_80_COM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_50_80_TECH',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_80_150_COM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='MTOW_80_150_TECH',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='NET_CABINE_100',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='NET_CABINE_200',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='NET_CABINE_300',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='OUV_DOSS_BAG',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='PASSERELLE_PSG',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='PLATEFORME',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='PLEIN_WATER_BIG_PORT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='PLEIN_WATER_MOY_PORT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='PORTE_CONTAINER_PALETTE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='PUSH_BACK',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='RECONC_BAG_BRS',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='TAPIS_BAG',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='TOWING',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='TRACT_CHARIOT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='USE_DCS',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='VEHICULE_TRANSP_PISTE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='VIDE_TOILET_BIG_PORT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='VIDE_TOILET_MOY_PORT',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='VIP_BUS',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='abs_demande',
            field=models.PositiveIntegerField(blank=True, db_column='ABSENCE DEMANDE', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='assist_jourferie',
            field=models.PositiveIntegerField(blank=True, db_column='ASSIST JOUR FERIE', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='assist_night',
            field=models.PositiveIntegerField(blank=True, db_column='ASSIST NIGHT', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='assist_weekend',
            field=models.PositiveIntegerField(blank=True, db_column='ASSIST WEEKEND', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='cnl_12',
            field=models.PositiveIntegerField(blank=True, db_column='CNL <= 12', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='cnl_12_24',
            field=models.PositiveIntegerField(blank=True, db_column='12 < CNL <= 24', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='reduction',
            field=models.PositiveIntegerField(blank=True, db_column='REDUCTION', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='rtr_1_3',
            field=models.PositiveIntegerField(blank=True, db_column='1 < RETARD <= 3', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='rtr_3_5',
            field=models.PositiveIntegerField(blank=True, db_column='3 < RETARD <= 5', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='rtr_5',
            field=models.PositiveIntegerField(blank=True, db_column='RETARD > 5', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comp_dispatcher',
            name='standby',
            field=models.PositiveIntegerField(blank=True, db_column='STAND BY', default=None, null=True),
        ),
    ]
