# Generated by Django 3.2 on 2021-06-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_rename_fichetouchee_fiche_touchee'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='fiche_received',
            field=models.BooleanField(db_column='FICHE RECUS', default=False, null=True),
        ),
    ]
