# Generated by Django 3.2 on 2021-06-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_exchange_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif_occas',
            name='status',
            field=models.TextField(db_column='STATUS', default='actual', null=True),
        ),
    ]
