# Generated by Django 3.2 on 2021-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_tarif_occas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_dispatcher',
            name='solde_date',
            field=models.DateField(blank=True, db_column='SOLDE DATE', null=True),
        ),
    ]
