# Generated by Django 3.2 on 2021-06-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_escales'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='escales',
            table='ESCALES',
        ),
    ]
