# Generated by Django 3.2 on 2021-06-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_escales_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESCALES',
        ),
    ]
