# Generated by Django 3.2 on 2021-06-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_delete_escales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESCALES',
            fields=[
                ('escale', models.TextField(db_column='ESCALE', primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, db_column='FULL NAME', null=True)),
                ('fiche_from', models.PositiveIntegerField(blank=True, db_column='FICHES FROM', default=0, null=True)),
                ('fiche_to', models.PositiveIntegerField(blank=True, db_column='FICHES TO', default=0, null=True)),
                ('nb_fiche_remain', models.PositiveIntegerField(blank=True, db_column='NB FICHE RESTANTES', default=0, null=True)),
                ('date_last_affect', models.DateField(blank=True, db_column='DATE LAST AFFECT', null=True)),
            ],
            options={
                'db_table': 'ESCALES',
            },
        ),
    ]
