# Generated by Django 3.2 on 2021-06-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_escales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='compagnie',
        ),
        migrations.AddField(
            model_name='profile',
            name='escale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.escales'),
        ),
    ]
