# Generated by Django 3.2 on 2021-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20210609_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='ACC_SALON',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ACU',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='AGENT_COORD',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='AGENT_OP_QUALIF',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='AGENT_SERV_PASSAGE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='AGENT_SERV_PISTE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ARRANGEMENT_CAB',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ASSIST_TRANSIT',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ASSIST_UM',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ASSIST_VIP',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ASSIST_WCH',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ASU',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='CAMION_ELEV',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='CHARIOT_BAG',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='CIVIERE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='COMM_SOL_COCKPIT',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='CONTAINER_PALETTE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='DB_MANIP_ULD',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='DEPORTEE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='DOSS_VOL_IMP',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ELEV_FOURCHE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='GPU',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='HUM',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='ID_BAG',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='NET_CABINE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='OUV_DOSS_BAG',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='PASSERELLE_PSG',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='PLATEFORME',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='PLEIN_WATER',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='PORTE_CONTAINER_PALETTE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='PUSH_BACK',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='RECONC_BAG_BRS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='TAPIS_BAG',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='TOWING',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='TRACT_CHARIOT',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='USE_DCS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='VEHICULE_TRANSP_PISTE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='VIDE_TOILET',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight_assist',
            name='VIP_BUS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
