# Generated by Django 3.2 on 2021-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20210609_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='assist_jourferie',
            field=models.BooleanField(blank=True, db_column='ASSIST JOUR FERIE', default=None, null=True),
        ),
    ]
