# Generated by Django 3.2 on 2021-06-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20210609_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche_touchee',
            name='escale',
            field=models.ForeignKey(blank=True, db_column='ESCALE', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.escales'),
        ),
    ]
