# Generated by Django 3.2 on 2021-06-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20210609_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='fiche_touchee_file',
            field=models.FileField(blank=True, null=True, upload_to='FICHES/'),
        ),
    ]
