# Generated by Django 3.2 on 2021-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_flight_assist_fiche_touchee_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_assist',
            name='fiche_touchee_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
