# Generated by Django 3.2 on 2021-06-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_flight_assist_fiche_touchee_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='cnl_cause_fiche',
            field=models.TextField(blank=True, choices=[(1, 'ERREUR'), (2, 'DISPARITION'), (3, 'ETAT DÉTÉRIORÉ')], db_column='CAUSE CNL FICHE', null=True),
        ),
        migrations.AlterField(
            model_name='flight_assist',
            name='fiche_touchee_file',
            field=models.FileField(blank=True, null=True, upload_to='fiches/'),
        ),
    ]
