# Generated by Django 3.2 on 2021-06-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20210610_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_assist',
            name='cnl_cause_fiche',
        ),
        migrations.AddField(
            model_name='fiche_touchee',
            name='cnl_cause_fiche',
            field=models.TextField(blank=True, choices=[(1, 'ERREUR'), (2, 'DISPARITION'), (3, 'ETAT DÉTÉRIORÉ')], db_column='CAUSE CNL FICHE', null=True),
        ),
    ]
