# Generated by Django 3.2 on 2021-06-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_fiche_touchee_cnl_cause_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='fiche_scannee_conforme_recieved',
            field=models.BooleanField(db_column='FICHE CONFORME RECUS', default=False, null=True),
        ),
    ]
