# Generated by Django 3.2 on 2021-06-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_flight_assist_fiche_scannee_conforme_recieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORIQUE_ADD_QUOTA',
            fields=[
                ('date_last_add', models.DateTimeField(auto_now=True, db_column='DATE LAST ADD', primary_key=True, serialize=False)),
                ('fiches_from', models.PositiveIntegerField(blank=True, db_column='FROM', null=True)),
                ('fiches_until', models.PositiveIntegerField(blank=True, db_column='UNTIL', null=True)),
            ],
            options={
                'db_table': 'HISTORIQUE_ADD_QUOTA',
            },
        ),
    ]
