# Generated by Django 3.2 on 2021-06-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_historique_add_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORIQUE_AFFECT_QUOTA',
            fields=[
                ('date_last_add', models.DateTimeField(auto_now=True, db_column='DATE LAST ADD', primary_key=True, serialize=False)),
                ('fiches_from', models.PositiveIntegerField(blank=True, db_column='FROM', null=True)),
                ('fiches_until', models.PositiveIntegerField(blank=True, db_column='UNTIL', null=True)),
                ('escale', models.ForeignKey(blank=True, db_column='ESCALE', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.escales')),
            ],
            options={
                'db_table': 'HISTORIQUE_AFFECT_QUOTA',
            },
        ),
    ]
