# Generated by Django 3.2 on 2021-06-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_historique_affect_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORIQUE_CNL_FICHES',
            fields=[
                ('date_last_cnl', models.DateTimeField(auto_now=True, db_column='DATE LAST CNL', primary_key=True, serialize=False)),
                ('fiches_from', models.PositiveIntegerField(blank=True, db_column='FROM', null=True)),
                ('fiches_until', models.PositiveIntegerField(blank=True, db_column='UNTIL', null=True)),
                ('cause', models.TextField(blank=True, db_column='CAUSE CNL', null=True)),
                ('obs', models.TextField(blank=True, db_column='OBS', null=True)),
            ],
            options={
                'db_table': 'HISTORIQUE_CNL_FICHES',
            },
        ),
    ]
