# Generated by Django 3.2 on 2021-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_flight_assist_n_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='dcs',
            field=models.FloatField(blank=True, db_column='DCS', null=True),
        ),
    ]
