# Generated by Django 3.2 on 2021-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_flight_assist_dcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_assist',
            name='dcs',
            field=models.FloatField(blank=True, db_column='DCS', default='0', null=True),
        ),
    ]
