# Generated by Django 3.2 on 2021-06-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_flight_assist_dcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_assist',
            name='heure_demande',
            field=models.TimeField(blank=True, db_column='HEURE DEMANDE', null=True),
        ),
    ]
