# Generated by Django 3.2 on 2021-06-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_historique_regular_fact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historique_regular_fact',
            table='HISTORIQUE_REGULAR_FACT',
        ),
    ]
