# Generated by Django 3.2 on 2021-06-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_historique_regular_fact_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HISTORIQUE_REGULAR_FACT',
        ),
    ]
