# Generated by Django 3.2 on 2021-06-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_historique_regular_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique_regular_fact',
            name='escale',
            field=models.ForeignKey(blank=True, db_column='ESCALE', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.escales'),
        ),
    ]
