# Generated by Django 3.2 on 2021-06-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_flight_assist_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dpt',
            field=models.TextField(blank=True, db_column='DPT', null=True),
        ),
    ]
