# Generated by Django 3.2 on 2021-06-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_profile_dpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='poste',
            field=models.TextField(blank=True, choices=[(1, 'SOUS DIRECTEUR GESTION DES ESCALES'), (2, 'CHEF DEPARTEMENT'), (3, 'CHEF DE SERVICE'), (4, 'AGENT'), (5, "CHEF D'ESCALE")]),
        ),
    ]
