# Generated by Django 3.2 on 2021-06-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_historique_regular_fact_user_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique_regular_fact',
            name='_id',
            field=models.PositiveIntegerField(db_column='ID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historique_regular_fact',
            name='date_last_add',
            field=models.DateTimeField(auto_now=True, db_column='DATE LAST ADD'),
        ),
    ]
