# Generated by Django 3.2 on 2021-06-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20210629_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique_regular_fact',
            name='_id',
            field=models.PositiveIntegerField(db_column='ID'),
        ),
        migrations.AlterField(
            model_name='historique_regular_fact',
            name='date_last_add',
            field=models.DateTimeField(auto_now=True, db_column='DATE LAST ADD', primary_key=True, serialize=False),
        ),
    ]
