# Generated by Django 3.2 on 2021-06-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_historique_regular_fact__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique_regular_fact',
            name='_id',
            field=models.PositiveIntegerField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historique_regular_fact',
            name='date_last_add',
            field=models.DateTimeField(auto_now=True, db_column='DATE LAST ADD', null=True),
        ),
    ]
