# Generated by Django 3.2 on 2021-06-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_remove_historique_regular_fact_date_last_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique_regular_fact',
            name='date_last_add',
            field=models.DateTimeField(auto_now=True, db_column='DATE LAST ADD', null=True),
        ),
    ]
