# Generated by Django 3.2 on 2021-06-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_historique_regular_fact_date_last_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HISTORIQUE_REGULAR_FACT',
        ),
    ]
