# Generated by Django 3.2 on 2021-06-29 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0116_delete_historique_regular_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORIQUE_REGULAR_FACT',
            fields=[
                ('_id', models.PositiveIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('date_last_add', models.DateTimeField(auto_now=True, db_column='DATE LAST ADD', null=True)),
                ('from_date', models.DateField(blank=True, db_column='FROM', null=True)),
                ('until_date', models.DateField(blank=True, db_column='UNTIL', null=True)),
                ('montant', models.FloatField(blank=True, db_column='MONTANT', null=True)),
                ('company', models.ForeignKey(blank=True, db_column='COMPANY', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comp_dispatcher')),
                ('escale', models.ForeignKey(blank=True, db_column='ESCALE', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.escales')),
                ('user_add', models.ForeignKey(blank=True, db_column='USER', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HISTORIQUE_REGULAR_FACT',
            },
        ),
    ]
