# Generated by Django 3.2 on 2021-06-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_historique_regular_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique_regular_fact',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
