# Generated by Django 3.2 on 2021-06-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_historique_regular_fact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique_regular_fact',
            name='type_fact',
            field=models.TextField(blank=True, db_column='TYPE FACT', null=True),
        ),
    ]
