# Generated by Django 3.2 on 2021-07-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_historique_op_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique_op_company',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
