# Generated by Django 3.2 on 2021-07-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_historique_op_company_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAG_RL',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('rl', models.TextField(blank=True, db_column='RL', null=True)),
            ],
        ),
    ]
