# Generated by Django 3.2 on 2021-07-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_bag_rl'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bag_rl',
            table='BAG_RL',
        ),
    ]
