# Generated by Django 3.2 on 2021-07-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_alter_bag_rl_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BAG_RL',
        ),
    ]
