# Generated by Django 3.2 on 2021-07-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_delete_bag_rl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAG_RL',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('rl', models.TextField(blank=True, db_column='RL', null=True)),
            ],
            options={
                'db_table': 'BAG_RL',
            },
        ),
    ]
