# Generated by Django 3.2 on 2021-07-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_bag_id_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BAG_ID_CHART',
        ),
    ]
