# Generated by Django 3.2 on 2021-07-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_bag_id_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAG_MRD_TYPE_DMG',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, db_column='LABEL', null=True)),
                ('desc', models.TextField(blank=True, db_column='DESC', null=True)),
            ],
            options={
                'db_table': 'BAG_MRD_TYPE_DMG',
            },
        ),
    ]
