# Generated by Django 3.2 on 2021-07-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_bag_mrd_type_dmg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAG_SUIVI',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_claim', models.DateTimeField(auto_now=True, db_column='DTE RECL', null=True)),
                ('escale_claim', models.TextField(blank=True, db_column='STATION', null=True)),
                ('file_type', models.TextField(blank=True, choices=[(1, 'AHL'), (2, 'DPR'), (3, 'OHD')], db_column='FILE TYPE', null=True)),
                ('ref', models.PositiveIntegerField(blank=True, db_column='REF', null=True)),
                ('flt', models.TextField(blank=True, db_column='FLT', null=True)),
                ('dte_flt', models.TextField(blank=True, db_column='FLT_DATE', null=True)),
                ('fs', models.TextField(blank=True, db_column='FS', null=True)),
                ('ft', models.TextField(blank=True, db_column='FT', null=True)),
                ('prov', models.TextField(blank=True, db_column='PROV', null=True)),
                ('dest', models.TextField(blank=True, db_column='DEST', null=True)),
                ('status', models.TextField(blank=True, choices=[(1, 'SUSPENDU'), (2, 'FERMÉ'), (3, 'REÇU')], null=True)),
                ('n_file', models.TextField(blank=True, db_column='N° FILE', null=True)),
                ('pax_gender', models.TextField(blank=True, db_column='GENDER', null=True)),
                ('pax_first_name', models.TextField(blank=True, db_column='PRENOM', null=True)),
                ('pax_last_name', models.TextField(blank=True, db_column='NOM', null=True)),
                ('pax_age', models.PositiveIntegerField(blank=True, db_column='AGE', null=True)),
                ('pax_adr_pax', models.TextField(blank=True, db_column='ADRESSE PAX', null=True)),
                ('pax_phone', models.CharField(blank=True, db_column='PHONE', max_length=10, null=True)),
                ('pax_mail', models.TextField(blank=True, db_column='MAIL', null=True)),
                ('pax_zip_code', models.PositiveIntegerField(blank=True, db_column='ZIP', null=True)),
                ('pax_reg', models.TextField(blank=True, db_column='REGION', null=True)),
                ('pax_country_res', models.TextField(blank=True, db_column='COUNTRY RES', null=True)),
                ('pax_delivery_phone', models.CharField(blank=True, db_column='DELIVERY PHONE', max_length=10, null=True)),
                ('pax_delivery_mail', models.TextField(blank=True, db_column='DELIVERY MAIL', null=True)),
                ('pax_delivery_adr', models.TextField(blank=True, db_column='DELIVERY ADDRESS', null=True)),
                ('n_tag', models.PositiveIntegerField(blank=True, db_column='TAG', null=True)),
                ('etkt', models.PositiveIntegerField(blank=True, db_column='ETKT', null=True)),
                ('carte_fid', models.PositiveIntegerField(blank=True, db_column='CARTE FID', null=True)),
                ('file_conforme', models.BooleanField(blank=True, db_column='CONFORME', default=False, null=True)),
                ('file_complet', models.BooleanField(blank=True, db_column='COMPLET', default=False, null=True)),
                ('bag_weight', models.FloatField(blank=True, db_column='WEIGHT', null=True)),
                ('bag_brand', models.TextField(blank=True, db_column='BRAND NAME', null=True)),
                ('bag_details', models.TextField(blank=True, db_column='DETAILS', null=True)),
                ('bag_phone', models.CharField(blank=True, db_column='PHONE ON BAG', max_length=10, null=True)),
                ('bag_id', models.TextField(blank=True, db_column='BAG ID', null=True)),
                ('content_dmg', models.TextField(blank=True, db_column='CONTENT DMG', null=True)),
                ('bag_dmg_mrd', models.TextField(blank=True, db_column='BAG DMG ID MRD', null=True)),
                ('dte_prop', models.DateField(blank=True, db_column='DATE PROPOSITION', null=True)),
                ('esc_dest', models.TextField(blank=True, db_column='DESTINATAIRE', null=True)),
                ('montant_dzd', models.FloatField(blank=True, db_column='DZD', null=True)),
                ('montant_eur', models.FloatField(blank=True, db_column='EUR', null=True)),
                ('montant_usd', models.FloatField(blank=True, db_column='USD', null=True)),
                ('accord', models.BooleanField(blank=True, default=False, null=True)),
                ('dte_sign', models.DateField(blank=True, db_column='DATE SIGN', null=True)),
                ('dpt_dest', models.TextField(blank=True, db_column='DPT DESTINATAIRE', null=True)),
                ('dte_send_payment', models.DateField(blank=True, db_column='DATE SEND PAYMENT', null=True)),
                ('dte_recept', models.DateField(blank=True, db_column='DATE RECEPT PAYMENT', null=True)),
                ('bord_env_ref', models.TextField(blank=True, db_column='REF BORD ENV', null=True)),
                ('bord_env_accord', models.BooleanField(blank=True, default=False, null=True)),
                ('rib_n', models.PositiveIntegerField(blank=True, db_column='RIB VALUE', null=True)),
                ('rib_key', models.PositiveIntegerField(blank=True, db_column='RIB KEY', null=True)),
                ('payment_status', models.TextField(blank=True, db_column='PAYMENT STATUS', null=True)),
                ('obs', models.TextField(blank=True, db_column='OBS', null=True)),
                ('rl', models.ForeignKey(blank=True, db_column='RL', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bag_rl')),
            ],
            options={
                'db_table': 'BAG_SUIVI',
            },
        ),
    ]
