# Generated by Django 3.2 on 2021-07-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_bag_suivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_suivi',
            name='search_status',
            field=models.TextField(blank=True, db_column='SEARCH STATUS', null=True),
        ),
    ]
