# Generated by Django 3.2 on 2021-07-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_bag_suivi_search_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag_suivi',
            name='pax_delivery_mail',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='pax_delivery_phone',
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='other_delivery_adr',
            field=models.TextField(blank=True, db_column='OTHER ADDRESS', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='other_delivery_mail',
            field=models.TextField(blank=True, db_column='OTHER MAIL', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='other_delivery_phone',
            field=models.CharField(blank=True, db_column='OTHER PHONE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='pax_stay_until',
            field=models.DateField(blank=True, db_column='DLV ADR STAYS UNTIL', null=True),
        ),
        migrations.AlterField(
            model_name='bag_suivi',
            name='status',
            field=models.TextField(blank=True, choices=[(0, 'NEW'), (1, 'SUSPENDU'), (2, 'FERMÉ'), (3, 'REÇU')], null=True),
        ),
    ]
