# Generated by Django 3.2 on 2021-07-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20210708_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_details',
            name='bag_adr',
            field=models.TextField(blank=True, db_column='ADRESS ON BAG', null=True),
        ),
    ]
