# Generated by Django 3.2 on 2021-07-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_bag_details_bag_adr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_suivi',
            name='date_last_edit',
            field=models.DateTimeField(auto_now=True, db_column='DATE LAST EDIT', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='user_last_edit',
            field=models.TextField(blank=True, db_column='USER LAST EDIT', null=True),
        ),
    ]
