# Generated by Django 3.2 on 2021-07-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_auto_20210710_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag_details',
            name='etkt',
            field=models.TextField(blank=True, db_column='ETKT', null=True),
        ),
        migrations.AlterField(
            model_name='bag_details',
            name='n_tag',
            field=models.TextField(blank=True, db_column='TAG', null=True),
        ),
    ]
