# Generated by Django 3.2 on 2021-07-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_auto_20210710_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag_suivi',
            name='date_claim',
            field=models.DateTimeField(blank=True, db_column='DTE RECL', null=True),
        ),
    ]
