# Generated by Django 3.2 on 2021-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_alter_bag_suivi_date_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_suivi',
            name='found',
            field=models.BooleanField(blank=True, db_column='FOUND', default=False, null=True),
        ),
    ]
