# Generated by Django 3.2 on 2021-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_bag_suivi_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag_suivi',
            name='accord',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
