# Generated by Django 3.2 on 2021-07-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_auto_20210712_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag_suivi',
            name='found',
        ),
        migrations.AddField(
            model_name='bag_details',
            name='found',
            field=models.BooleanField(blank=True, db_column='FOUND', default=False, null=True),
        ),
    ]
