# Generated by Django 3.2 on 2021-07-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20210712_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag_suivi',
            name='file_complet',
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='conf_reason',
            field=models.TextField(blank=True, db_column='CONF_REASON', null=True),
        ),
        migrations.AlterField(
            model_name='bag_suivi',
            name='status',
            field=models.TextField(blank=True, choices=[(0, 'RECH. PRIMAIRE'), (1, 'RECH. SECONDAIRE'), (2, 'SUSPENDU'), (3, "EN COURS D'INDEMNISATION"), (4, 'CLÔTURÉ')], null=True),
        ),
    ]
