# Generated by Django 3.2 on 2021-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_auto_20210712_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag_suivi',
            name='other_delivery_adr',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='other_delivery_mail',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='other_delivery_phone',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='pax_adr_pax',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='pax_delivery_adr',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='pax_phone',
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='pax_adr_pax_1',
            field=models.TextField(blank=True, db_column='ADRESSE PAX 1', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='pax_adr_pax_2',
            field=models.TextField(blank=True, db_column='ADRESSE PAX 2', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='pax_phone_1',
            field=models.CharField(blank=True, db_column='PHONE 1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='pax_phone_2',
            field=models.CharField(blank=True, db_column='PHONE 2', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='pax_phone_3',
            field=models.CharField(blank=True, db_column='PHONE 3', max_length=10, null=True),
        ),
    ]
