# Generated by Django 3.2 on 2021-07-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20210712_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag_suivi',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='dte_flt',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='flt',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='prov',
        ),
        migrations.CreateModel(
            name='BAG_FLIGHTS',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_tranc', models.PositiveIntegerField(blank=True, db_column='N TRANC', null=True)),
                ('company', models.TextField(blank=True, db_column='COMPANY', null=True)),
                ('flt', models.TextField(blank=True, db_column='FLT', null=True)),
                ('dte_flt', models.TextField(blank=True, db_column='FLT_DATE', null=True)),
                ('prov', models.TextField(blank=True, db_column='PROV', null=True)),
                ('dest', models.TextField(blank=True, db_column='DEST', null=True)),
                ('suivi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bag_suivi')),
            ],
            options={
                'db_table': 'BAG_FLIGHTS',
            },
        ),
    ]
