# Generated by Django 3.2 on 2021-07-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20210712_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag_suivi',
            name='fs',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='ft',
        ),
        migrations.AddField(
            model_name='bag_flights',
            name='fs',
            field=models.TextField(blank=True, db_column='FS', null=True),
        ),
        migrations.AddField(
            model_name='bag_flights',
            name='ft',
            field=models.TextField(blank=True, db_column='FT', null=True),
        ),
    ]
