# Generated by Django 3.2 on 2021-07-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20210712_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag_details',
            name='etkt',
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='etkt',
            field=models.TextField(blank=True, db_column='ETKT', null=True),
        ),
    ]
