# Generated by Django 3.2 on 2021-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_bag_suivi_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_flights',
            name='bag_status',
            field=models.BooleanField(blank=True, db_column='STATUS', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='dte_send_bcr',
            field=models.DateTimeField(blank=True, db_column='DATE ENVOIE', null=True),
        ),
    ]
