# Generated by Django 3.2 on 2021-07-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20210713_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_suivi',
            name='n_bag_miss_dmg',
            field=models.PositiveIntegerField(blank=True, db_column='NB BAG MISS DMG', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='n_bag_received',
            field=models.PositiveIntegerField(blank=True, db_column='NB BAG RECUS', null=True),
        ),
    ]
