# Generated by Django 3.2 on 2021-07-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_bag_suivi_n_recu_payment_exc_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_flights',
            name='flt_obs',
            field=models.TextField(blank=True, db_column='OBS', null=True),
        ),
    ]
