# Generated by Django 3.2 on 2021-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_bag_flights_flt_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag_flights',
            name='bag_status',
        ),
        migrations.AddField(
            model_name='bag_details',
            name='bag_status',
            field=models.BooleanField(blank=True, db_column='STATUS', null=True),
        ),
    ]
