# Generated by Django 3.2 on 2021-07-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_auto_20210714_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag_details',
            old_name='content_dmg',
            new_name='bag_content_dmg',
        ),
        migrations.RenameField(
            model_name='bag_details',
            old_name='found',
            new_name='bag_found',
        ),
        migrations.RenameField(
            model_name='bag_details',
            old_name='n_tag',
            new_name='bag_n_tag',
        ),
        migrations.RenameField(
            model_name='bag_details',
            old_name='obs',
            new_name='bag_obs',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='accord',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='dte_prop',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='esc_dest',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='montant_dzd',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='montant_eur',
        ),
        migrations.RemoveField(
            model_name='bag_suivi',
            name='montant_usd',
        ),
        migrations.AlterField(
            model_name='bag_suivi',
            name='status',
            field=models.TextField(blank=True, choices=[(0, 'RECH. PRIMAIRE'), (1, 'RECH. SECONDAIRE'), (2, 'SUSPENDU'), (3, "EN COURS D'INDEMNISATION"), (4, 'CLOSED')], null=True),
        ),
        migrations.CreateModel(
            name='BAG_HIST_INDEMN',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('dte_prop', models.DateField(blank=True, db_column='DATE PROPOSITION', null=True)),
                ('esc_dest', models.TextField(blank=True, db_column='DESTINATAIRE', null=True)),
                ('monnaie', models.TextField(blank=True, db_column='MONNAIE', null=True)),
                ('montant_dzd', models.FloatField(blank=True, db_column='DZD', null=True)),
                ('montant_eur', models.FloatField(blank=True, db_column='EUR', null=True)),
                ('montant_usd', models.FloatField(blank=True, db_column='USD', null=True)),
                ('accord', models.BooleanField(blank=True, null=True)),
                ('suivi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bag_suivi')),
            ],
            options={
                'db_table': 'BAG_HIST_INDEMN',
            },
        ),
    ]
