# Generated by Django 3.2 on 2021-07-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20210716_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag_suivi',
            name='payment_status',
            field=models.BooleanField(blank=True, db_column='PAYMENT STATUS', null=True),
        ),
    ]
