# Generated by Django 3.2 on 2021-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_alter_bag_suivi_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_suivi',
            name='id_dte_deliv',
            field=models.DateField(blank=True, db_column='DTE DELIV ID', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='id_num',
            field=models.TextField(blank=True, db_column='NUM ID', null=True),
        ),
        migrations.AddField(
            model_name='bag_suivi',
            name='id_type',
            field=models.TextField(blank=True, db_column='TYPE ID', null=True),
        ),
    ]
