# Generated by Django 3.2 on 2021-07-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20210717_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_suivi',
            name='id_geo_deliv',
            field=models.TextField(blank=True, db_column='LIEU DELIV ID', null=True),
        ),
    ]
