# Generated by Django 3.2 on 2021-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20210718_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_flights',
            name='miles',
            field=models.FloatField(blank=True, db_column='MILES', null=True),
        ),
    ]
