# Generated by Django 3.2 on 2021-07-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_bag_flights_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag_flights',
            name='currency',
            field=models.TextField(blank=True, db_column='CURRENCY', null=True),
        ),
        migrations.AddField(
            model_name='bag_flights',
            name='montant_fct',
            field=models.FloatField(blank=True, db_column='MONTANT FACT', null=True),
        ),
    ]
