# Generated by Django 3.2 on 2021-07-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_auto_20210718_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='date_last_edit',
        ),
        migrations.AddField(
            model_name='exchange',
            name='date_begin',
            field=models.DateTimeField(auto_now_add=True, db_column='DATE LAST EDIT', null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
