# Generated by Django 3.2 on 2021-07-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_auto_20210719_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique_regular_fact',
            name='n_facture',
            field=models.TextField(blank=True, db_column='N° FACTURE', null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='date_begin',
            field=models.DateTimeField(blank=True, db_column='DATE LAST EDIT', null=True),
        ),
    ]
